#!/usr/bin/env python3
"""
search_engine.py

A unified GraphRAG search CLI tool using Microsoft GraphRAG with LiteLLM
and Google Gemini 2.5 Flash Lite model.

This script implements four GraphRAG search methods:
1. Global Search - Map-reduce search over community reports
2. Local Search - Contextual search over entities, relationships, covariates, and text units
3. DRIFT Search - Dynamic Reasoning and Information Traversal Search
4. Basic Search - Standard vector-based RAG search over text unit chunks

Requirements:
- graphrag
- litellm
- pandas
- pyarrow
- lancedb

Usage Examples:
  python search_engine.py --mode global --query "What are the major themes in the dataset?"
  python search_engine.py --mode local --query "Tell me about Entity X"
  python search_engine.py --mode drift --query "How does Component A interact with Component B?"
  python search_engine.py --mode basic --query "Find references to project milestones"
"""

import asyncio
import argparse
import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

import pandas as pd
from dotenv import load_dotenv
load_dotenv()

# Import GraphRAG configuration, LLM config, and data adapter utilities
from graphrag.config.models.graph_rag_config import GraphRagConfig
from graphrag_llm.config import ModelConfig
from graphrag.query.indexer_adapters import (
    read_indexer_entities,
    read_indexer_relationships,
    read_indexer_reports,
    read_indexer_text_units,
    read_indexer_communities,
    read_indexer_covariates,
)
from graphrag.query.factory import (
    get_global_search_engine,
    get_local_search_engine,
    get_drift_search_engine,
    get_basic_search_engine,
)
from graphrag_vectors.lancedb import LanceDBVectorStore

# Monkeypatch LiteLLMCompletion to support both Local (awaiting) and Basic (async iterating) search patterns
from graphrag_llm.completion.lite_llm_completion import LiteLLMCompletion

original_completion_async = LiteLLMCompletion.completion_async

class AwaitableAsyncIterator:
    def __init__(self, coro):
        self.coro = coro
        self.iterator = None

    def __await__(self):
        return self.coro.__await__()

    async def _ensure_iterator(self):
        if self.iterator is None:
            self.iterator = await self.coro
        return self.iterator

    def __aiter__(self):
        return self

    async def __anext__(self):
        iterator = await self._ensure_iterator()
        if not hasattr(iterator, "__anext__"):
            raise TypeError("completion_async result is not an async iterator when stream=False")
        return await iterator.__anext__()

def patched_completion_async(self, *args, **kwargs):
    coro = original_completion_async(self, *args, **kwargs)
    return AwaitableAsyncIterator(coro)

LiteLLMCompletion.completion_async = patched_completion_async



def load_parquet_tables(output_dir: Path) -> Dict[str, pd.DataFrame]:
    """
    Loads Parquet files generated by the GraphRAG indexing pipeline.

    Expected files in output directory:
    - create_final_entities.parquet / entities.parquet
    - create_final_relationships.parquet / relationships.parquet
    - create_final_community_reports.parquet / community_reports.parquet
    - create_final_text_units.parquet / text_units.parquet
    - create_final_communities.parquet / communities.parquet
    - create_final_covariates.parquet / covariates.parquet (optional)
    """
    tables = {}

    file_mappings = {
        "entities": ["create_final_entities.parquet", "entities.parquet"],
        "relationships": ["create_final_relationships.parquet", "relationships.parquet"],
        "reports": ["create_final_community_reports.parquet", "community_reports.parquet"],
        "text_units": ["create_final_text_units.parquet", "text_units.parquet"],
        "communities": ["create_final_communities.parquet", "communities.parquet"],
        "covariates": ["create_final_covariates.parquet", "covariates.parquet"],
    }

    for key, filenames in file_mappings.items():
        found = False
        for fname in filenames:
            file_path = output_dir / fname
            if file_path.exists():
                tables[key] = pd.read_parquet(file_path)
                found = True
                break
        if not found:
            tables[key] = pd.DataFrame()

    return tables


def build_graphrag_config(
    llm_api_key: str,
    emb_api_key: str,
    llm_model: str = "openai/gpt-4o-mini",
    embedding_model: str = "gemini/gemini-embedding-001",
) -> GraphRagConfig:
    """
    Constructs GraphRagConfig configured for LiteLLM with OpenAI/Gemini models.
    """
    def parse_model(model_str: str, default_provider: str = "gemini"):
        if "/" in model_str:
            parts = model_str.split("/", 1)
            return parts[0], parts[1]
        return default_provider, model_str

    llm_provider, llm_name = parse_model(llm_model)
    emb_provider, emb_name = parse_model(embedding_model)

    completion_config = ModelConfig(
        model=llm_name,
        api_key=llm_api_key,
        model_provider=llm_provider,
    )

    embedding_config = ModelConfig(
        model=emb_name,
        api_key=emb_api_key,
        model_provider=emb_provider,
    )

    config = GraphRagConfig(
        completion_models={
            "default": completion_config,
            "default_completion_model": completion_config
        },
        embedding_models={
            "default": embedding_config,
            "default_embedding_model": embedding_config
        },
    )
    return config


def initialize_vector_store(
    db_uri: str,
    collection_name: str,
) -> LanceDBVectorStore:
    """
    Initializes a LanceDB vector store for entity descriptions or text units embeddings.
    """
    store = LanceDBVectorStore(
        db_uri=db_uri,
        index_name=collection_name,
    )
    store.connect()
    return store


async def run_global_search(
    query: str,
    config: GraphRagConfig,
    tables: Dict[str, pd.DataFrame],
    community_level: Optional[int] = None,
    response_type: str = "multiple paragraphs",
) -> str:
    """
    Executes Global Search across community reports using map-reduce approach.
    """
    reports = read_indexer_reports(
        final_community_reports=tables["reports"],
        final_communities=tables["communities"],
        community_level=community_level,
    )
    entities = read_indexer_entities(
        entities=tables["entities"],
        communities=tables["communities"],
        community_level=community_level,
    )
    communities = read_indexer_communities(
        final_communities=tables["communities"],
        final_community_reports=tables["reports"],
    )

    search_engine = get_global_search_engine(
        config=config,
        reports=reports,
        entities=entities,
        communities=communities,
        response_type=response_type,
        dynamic_community_selection=True
    )

    result = await search_engine.search(query)
    return result.response


async def run_local_search(
    query: str,
    config: GraphRagConfig,
    tables: Dict[str, pd.DataFrame],
    lancedb_dir: str,
    community_level: Optional[int] = None,
    response_type: str = "multiple paragraphs",
) -> str:
    """
    Executes Local Search combining entity details, relationships, covariates, and text units.
    """
    reports = read_indexer_reports(
        final_community_reports=tables["reports"],
        final_communities=tables["communities"],
        community_level=community_level,
    )
    text_units = read_indexer_text_units(tables["text_units"])
    entities = read_indexer_entities(
        entities=tables["entities"],
        communities=tables["communities"],
        community_level=community_level,
    )
    relationships = read_indexer_relationships(tables["relationships"])
    covariates = (
        {"claims": read_indexer_covariates(tables["covariates"])}
        if not tables["covariates"].empty
        else {}
    )

    description_embedding_store = initialize_vector_store(
        db_uri=lancedb_dir,
        collection_name="entity_description",
    )

    search_engine = get_local_search_engine(
        config=config,
        reports=reports,
        text_units=text_units,
        entities=entities,
        relationships=relationships,
        covariates=covariates,
        response_type=response_type,
        description_embedding_store=description_embedding_store,
    )

    result = await search_engine.search(query)
    return result.response


async def run_drift_search(
    query: str,
    config: GraphRagConfig,
    tables: Dict[str, pd.DataFrame],
    lancedb_dir: str,
    community_level: Optional[int] = None,
    response_type: str = "multiple paragraphs",
) -> str:
    """
    Executes DRIFT Search (Dynamic Reasoning and Information Traversal Search).
    """
    reports = read_indexer_reports(
        final_community_reports=tables["reports"],
        final_communities=tables["communities"],
        community_level=community_level,
    )
    from graphrag.query.indexer_adapters import read_indexer_report_embeddings
    reports_embeddings_store = initialize_vector_store(
        db_uri=lancedb_dir,
        collection_name="community_full_content",
    )
    read_indexer_report_embeddings(reports, reports_embeddings_store)
    text_units = read_indexer_text_units(tables["text_units"])
    entities = read_indexer_entities(
        entities=tables["entities"],
        communities=tables["communities"],
        community_level=community_level,
    )
    relationships = read_indexer_relationships(tables["relationships"])

    description_embedding_store = initialize_vector_store(
        db_uri=lancedb_dir,
        collection_name="entity_description",
    )

    search_engine = get_drift_search_engine(
        config=config,
        reports=reports,
        text_units=text_units,
        entities=entities,
        relationships=relationships,
        description_embedding_store=description_embedding_store,
        response_type=response_type,
    )

    result = await search_engine.search(query)
    return result.response


async def run_basic_search(
    query: str,
    config: GraphRagConfig,
    tables: Dict[str, pd.DataFrame],
    lancedb_dir: str,
    response_type: str = "multiple paragraphs",
) -> str:
    """
    Executes Basic Search over text unit vector embeddings.
    """
    text_units = read_indexer_text_units(tables["text_units"])
    text_unit_embeddings = initialize_vector_store(
        db_uri=lancedb_dir,
        collection_name="text_unit_text",
    )

    search_engine = get_basic_search_engine(
        text_units=text_units,
        text_unit_embeddings=text_unit_embeddings,
        config=config,
        response_type=response_type,
    )

    result = await search_engine.search(query)
    return result.response


def parse_args(query, plan):
    parser = argparse.ArgumentParser(
        description="Microsoft GraphRAG 4-Method Search Engine using LiteLLM and Gemini"
    )
    parser.add_argument(
        "--mode",
        choices=["global", "local", "drift", "basic"],
        default=plan,
        help="Search method to execute",
    )
    parser.add_argument(
        "--query",
        type=str,
        default=query,
        help="Query text to search for",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="./output",
        help="Directory containing indexing Parquet outputs (default: ./output)",
    )
    parser.add_argument(
        "--lancedb_dir",
        type=str,
        default="./output/lancedb",
        help="Directory containing LanceDB vector indices (default: ./output/lancedb)",
    )
    parser.add_argument(
        "--api_key",
        type=str,
        default=os.getenv("OPENAI_API_KEY", "default_key"),
        help="OpenAI API key (defaults to OPENAI_API_KEY env variable)",
    )
    parser.add_argument(
        "--model",
        type=str,
        default="openai/gpt-4o-mini",
        help="LiteLLM model identifier (default: openai/gpt-4o-mini)",
    )
    parser.add_argument(
        "--response_type",
        type=str,
        default="multiple paragraphs",
        help="Desired response formatting style",
    )

    return parser.parse_args()


async def GraphRAGQueryEngine(query, plan):
    args = parse_args(query, plan)

    output_dir = Path(args.output_dir)
    print(f"Loading Parquet artifacts from: {output_dir}")
    tables = load_parquet_tables(output_dir)

    print(f"Initializing GraphRAG configuration with model: {args.model}")
    config = build_graphrag_config(
        llm_api_key=args.api_key,
        emb_api_key=os.getenv("GEMINI_API_KEY", args.api_key),
        llm_model=args.model,
    )

    print(f"\nExecuting [{args.mode.upper()}] Search...")
    print(f"Query: {args.query}\n" + "-" * 50)

    if args.mode == "global":
        response = await run_global_search(
            query=args.query,
            config=config,
            tables=tables,
            response_type=args.response_type,
        )
    elif args.mode == "local":
        response = await run_local_search(
            query=args.query,
            config=config,
            tables=tables,
            lancedb_dir=args.lancedb_dir,
            response_type=args.response_type,
        )
    elif args.mode == "drift":
        response = await run_drift_search(
            query=args.query,
            config=config,
            tables=tables,
            lancedb_dir=args.lancedb_dir,
            response_type=args.response_type,
        )
    elif args.mode == "basic":
        response = await run_basic_search(
            query=args.query,
            config=config,
            tables=tables,
            lancedb_dir=args.lancedb_dir,
            response_type=args.response_type,
        )
    else:
        raise ValueError(f"Unsupported search mode: {args.mode}")

    return response


# if __name__ == "__main__":
#     if len(sys.argv) > 1 and sys.argv[1] in ("-h", "--help"):
#         parse_args()
#     else:
#         asyncio.run(main())
